# Please read https://book.getfoundry.sh/reference/config/solidity-compiler for additional config info
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.24'

[fmt]
# These are all the `forge fmt` defaults. (Formatting)
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
ignore = ["src/console.sol", "src/console2.sol"]
